-- framework
audio = require "framework.audio"
constant = require "framework.constant"
db = require "framework.db"
device = require "framework.device"
director = require "framework.director"
display = require "framework.display"
eventCenter = require "framework.eventCenter"
gScheduler = require "framework.gScheduler"
language = require "framework.language"
net = require "framework.net"
package_support = require "framework.package_support"
toolkit = require "framework.toolkit"
transition = require "framework.transition"
ttLoader = require "framework.ttLoader"
ui = require "framework.ui"
utf8 = require "framework.utf8"

ResMgr = require "framework.ResMgr"
LayerMgr = require "framework.LayerMgr"
LayerStack = require "framework.LayerStack"